language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: SNW0w7oQehnQLaOgpY0kSEkqmXMsM8Gjo2b54ULqB2tHu7HS+d3iJsGtoQGh5ASNL/yhqxa7Ufa6CeRJEO9yR+BJp919L4g2fcmMRI1GryKKzuH5Zob5WchHBYymMxy56RPIGbLMwdLCQw19NuNkIUsK+K0GtxUdRdVc0njrplNh+INSc2lhzWwC9wy/6pu0rxb7o/lkK1WfJ6kFVp3PCaCNCp6bbbkk8EK0aV3Geym2l9uezqwpljbrUTDx/sRxcvO+P6HVujVMo25mtwKA1G+xMbgUNFJ09RWloxksI13N0Wov+seU+GQfwk8rxUXB7EqBTuI8w84cdOp3784fAxCgKKWSUpexpKX3N2qUkUYekQCGTYa352MTfPc/XTQXwv9X0QYQyjsm4ZUy8vja7pAkhzKb8JaTwqoisvi7Zl7fYXqmyN5ljdgZzgsomb3T7QCxKJdYDY94hbp8XcU5wxMjqlgufjZj5JHk5VCQVtHhfdCvZJGGQrcgkaUS5IxA7WC9UWqpxn5U0Hkul4sIsl0sEYCeZFlk7FZ/CH6imGqYN5uBTv2ICKhshgpfxJ8SkV4V7315a3reOtBPLZwxDhvVWgIy9D59VNHs6/sTXLIoYHx4VIvObfdI4N5ZneeZLmM9uccjJF0jOas1S2UKPdOAi2VCfvYSC1yqa0pgvMQ=
  app: find-and-register-for-events
  on:
    repo: brandylavoy/node-capstone-find-and-register-for-events
